version: '2.1'
services:
  acceptance_test:
    build: .
    environment:
      - APP_URL
      - APP_URL_PREFIX
      - CAPYBARA_DRIVER
      - FEATURE_SET
      - ACCEPTANCE_TEST_USER
      - ACCEPTANCE_TEST_PASSWORD
    command: rake
