REPOSITORY_NAME ?= cwds/acceptance_testing
REPOSITORY_TAG := $(shell echo $$(git rev-parse --short HEAD))

.PHONY: build publish test clean
.DEFAULT_GOAL := build

# Set shell
SHELL=/bin/bash -e -o pipefail

# Cosmetics
RED := "\e[1;31m"
YELLOW := "\e[1;33m"
NC := "\e[0m"
ARROW := "\xe2\x87\x92"
INFO := @bash -c 'printf $(YELLOW); printf $(ARROW); echo " $$1"; printf $(NC)' MESSAGE
WARNING := @bash -c 'printf $(RED); echo "WARNING: $$1"; printf $(NC)' MESSAGE
